version: "2"
services:
  nginx:
    image: daocloud.io/library/nginx:1.17.8
    container_name: "nginx_service"
    restart: always
    links:
      - php-fpm
    depends_on:
      - php-fpm
    volumes:
      - "./configs/nginx/conf.d:/etc/nginx/conf.d"
      - "./log/nginx:/var/log/nginx"
      - "./www:/var/www"
    ports:
      - "80:80"
      - "443:443"
  php-fpm:
    image: registry.cn-hangzhou.aliyuncs.com/tiredoy/php-7.3:2.1
    container_name: "php_service"
    links:
      - mysql
      - redis
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
      - "./www:/var/www"
      - "./log/php:/var/log"
  mysql:
    image: daocloud.io/library/mysql:5.7
    container_name: "mysql_service"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./configs/mysql:/etc/mysql
      - ./db_data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
  redis:
    image: daocloud.io/library/redis:5.0
    container_name: "redis_service"
    volumes:
      - "./configs/redis/redis.conf:/usr/local/redis.conf"
      - "./db_data/redis/:/usr/local/redis/data/"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always
    privileged: true
    command: "redis-server /usr/local/redis.conf"
